package com.example.myapplication

data class Hobby(var title: String)

object Supplier {
    val hobbies = listOf<Hobby>(

        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
        Hobby("Work"),
        Hobby("Play"),
        Hobby("Walk"),
        Hobby("Eating"),
        Hobby("Learn"),
        Hobby("Enjoy"),
        Hobby("Free"),
    )
}